<?php

function budts_be_updater_install() {
  variable_set('install_profile', 'budts_be');

  $batch = array(
    'title' => 'Preparing budts.be for upgrade to Drupal 7',
    'operations' => array(
      array('budts_be_updater_batch_delete_nodes', array('image')),
      array('budts_be_updater_batch_delete_nodes', array('project_issue')),
      array('budts_be_updater_batch_delete_nodes', array('project_project')),
      array('budts_be_updater_batch_module_uninstall', array('image_import')),
      array('budts_be_updater_batch_module_uninstall', array('image_gallery')),
      array('budts_be_updater_batch_module_uninstall', array('image')),
      array('budts_be_updater_batch_module_uninstall', array('project')),
      array('budts_be_updater_batch_module_uninstall', array('project_issue')),
      array('budts_be_updater_batch_module_uninstall', array('custom_pagers')),
      array('budts_be_updater_batch_module_uninstall', array('custom_breadcrumbs_paths')),
      array('budts_be_updater_batch_module_uninstall', array('comment_upload')),
      array('budts_be_updater_batch_module_uninstall', array('admin_menu')),
      array('budts_be_updater_batch_module_uninstall', array('badbehavior')),
      array('budts_be_updater_batch_module_uninstall', array('advanced_help')),
      array('budts_be_updater_batch_module_uninstall', array('devel')),
      array('budts_be_updater_batch_module_uninstall', array('devel_themer')),
      array('budts_be_updater_batch_module_uninstall', array('globalredirect')),
      array('budts_be_updater_batch_module_uninstall', array('search404')),
      array('budts_be_updater_batch_delete_content_type', array('image')),
      array('budts_be_updater_batch_delete_content_type', array('project_issue')),
      array('budts_be_updater_batch_delete_content_type', array('project_project')),
      array('budts_be_updater_batch_delete_vocabulary', array(5)),
      array('budts_be_updater_batch_delete_view', array('image_gallery')),
    ),
    'finished' => 'budts_be_updater_batch_finished',
    'file' => dirname(__FILE__).'/budts_be_updater.install',
  );

  batch_set($batch);
}

function budts_be_updater_batch_delete_nodes($type, &$context) {
  $deleted = 0;
  $context['finished'] = 0;

  $query = db_query("select nid from {node} where type = '%s' limit 0, 25", $type);
  while ($res = db_fetch_array($query)) {
    node_delete($res['nid']);
    $deleted++;
  }

  if ($deleted < 25) {
    $context['finished'] = 1;
  }

  $context['sandbox']['deleted'] = $deleted + (isset($context['sandbox']['deleted']) ? intval($context['sandbox']['deleted']) : 0);
  $context['message'] = t('Deleted @number nodes of content type @type', array('@number' => $context['sandbox']['deleted'], '@type' => $type));
}

function budts_be_updater_batch_delete_content_type($type, &$context) {
  node_type_delete($type);
  node_types_rebuild();
  $context['finished'] = 1;
}

function budts_be_updater_batch_module_uninstall($module, &$context) {
  require_once './includes/install.inc';
  module_disable(array($module));
  drupal_uninstall_module($module);
  $context['finished'] = 1;
}

function budts_be_updater_batch_delete_vocabulary($vid, &$context) {
  module_load_include('module', 'taxonomy');
  taxonomy_del_vocabulary($vid);
  $context['finished'] = 1;
}

function budts_be_updater_batch_delete_view($view_name, &$context) {
  module_load_include('module', 'views');
  $view = views_get_view($view_name);
  if (!is_null($view)) {
    $view->delete();
  }
  $context['finished'] = 1;
}

